name = "card-tab-pages"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "CARD_ORDER"
id = "YOUR_KV_NAMESPACE_ID"

[[vars]]
ADMIN_PASSWORD = "PLACEHOLDER"
USER_ID = "testUser"
NAV_TITLE = "我的导航"